# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: cocoo's blog
email: 8427003@qq.com
description: www.css3.io css3.io cocoo cocoo.li blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.css3.io" # the base hostname & protocol for your site
github_username:  8427003
permalink: none
# Build settings
markdown: kramdown
